// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MijnKunst.web.Data;

#nullable disable

namespace MijnKunst.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915130846_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MijnKunst.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Nancy",
                            LastName = "Bailleux",
                            PlaceOfBirth = "Antwerpen",
                            YearOfBirth = "1964"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "",
                            LastName = "Banksy",
                            PlaceOfBirth = "Yate (UK)",
                            YearOfBirth = "1974"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Gerrit",
                            LastName = "Baten",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1959"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Etienne",
                            LastName = "Bauwens",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1930"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Geert",
                            LastName = "Bauwens",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1961"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "René",
                            LastName = "Bekaert",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1938"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "André",
                            LastName = "Berner",
                            PlaceOfBirth = "Vilvoorde",
                            YearOfBirth = "1955"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Walter",
                            LastName = "Brems",
                            PlaceOfBirth = "Reet",
                            YearOfBirth = "1947"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Pedro",
                            LastName = "Brugada",
                            PlaceOfBirth = "Girona (ESP)",
                            YearOfBirth = "1952"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "André",
                            LastName = "Bruylandt",
                            PlaceOfBirth = "Onkerzele",
                            YearOfBirth = "1944"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Roland",
                            LastName = "Cobbaut",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Claire",
                            LastName = "Cocquyt",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "",
                            LastName = "Expha",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Carla",
                            LastName = "Heuvinck",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "",
                            LastName = "MarieAnge",
                            PlaceOfBirth = "Nieuwpoort",
                            YearOfBirth = "1963"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Martina",
                            LastName = "Mory",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Jacky",
                            LastName = "Zegers",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Pieter",
                            LastName = "De Poortere",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = "1976"
                        });
                });

            modelBuilder.Entity("MijnKunst.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TechnicId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("MijnKunst.Models.Technic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acryl"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aquarel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aquarel & fineliner"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aquatint"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bister"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Balpen & markers"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cement"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ets"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ets, droge naald"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gemengde techniek"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gouache"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Houtsnede"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Keramiek"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Klei"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kleurpotlood"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Linosnede"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Nagellak"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Litho"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Offset druk"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Olieverf"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Oostindische inkt"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Opgehoogde zeefdruk"
                        },
                        new
                        {
                            Id = 23,
                            Name = "PC grafiek"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Print op doek"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Print op fotopapier"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Resin"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Zeefdruk"
                        });
                });

            modelBuilder.Entity("MijnKunst.Models.Artwork", b =>
                {
                    b.HasOne("MijnKunst.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MijnKunst.Models.Technic", "Technic")
                        .WithMany()
                        .HasForeignKey("TechnicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Technic");
                });
#pragma warning restore 612, 618
        }
    }
}
